sonar.projectKey=HCCM-Consulting_mail-daily-digest
sonar.projectName=mail-daily-digest
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
